import "./global.css";
import React from "react";
import { NavBar } from "./components/NavBar";

export const metadata = {
  title: "Welcome to frontend",
  description: "Generated by create-nx-workspace",
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en" className={"overflow-x-hidden overflow-y-hidden bg-background"}>
      <body>
        <NavBar />
        {children}
      </body>
    </html>
  );
}
